import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "store.db")


def create_database():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT,
            price REAL,
            description TEXT,
            is_organic INTEGER DEFAULT 0
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS reviews (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER,
            rating REAL,
            reviewer_name TEXT,
            review_text TEXT,
            FOREIGN KEY (product_id) REFERENCES products(id)
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER NOT NULL,
            product_name TEXT NOT NULL,
            price REAL NOT NULL,
            ordered_at TEXT NOT NULL DEFAULT (datetime('now')),
            FOREIGN KEY (product_id) REFERENCES products(id)
        )
    """)

    products = [
        # ── Honey (8) ─────────────────────────────────────────────────────────
        (1,   "Organic Raw Honey",                   "honey",         1409.06, "Pure organic raw honey, unfiltered and cold-pressed",                                     1),
        (2,   "Wildflower Honey",                    "honey",         1221.06, "Natural wildflower honey from local beekeepers",                                          0),
        (3,   "Organic Manuka Honey",                "honey",         2819.06, "Premium organic Manuka honey from New Zealand",                                           1),
        (4,   "Clover Honey",                        "honey",          845.06, "Classic clover honey, smooth and sweet",                                                  0),
        (5,   "Organic Buckwheat Honey",             "honey",         1785.06, "Dark and robust organic buckwheat honey, antioxidant-rich",                               1),
        (6,   "Orange Blossom Honey",                "honey",         1503.06, "Light and floral orange blossom honey",                                                   0),
        (7,   "Organic Acacia Honey",                "honey",         1691.06, "Light and mild organic acacia honey, low glycemic index",                                 1),
        (8,   "Creamed Honey",                       "honey",         1127.06, "Smooth creamed honey with spreadable texture",                                            0),
        # ── Oils (4) ──────────────────────────────────────────────────────────
        (9,   "Organic Extra Virgin Olive Oil",      "oil",           1597.06, "Cold-pressed organic EVOO from Mediterranean olives",                                     1),
        (10,  "Coconut Oil",                         "oil",           1174.06, "Refined coconut oil, great for high-heat cooking",                                        0),
        (11,  "Organic Flaxseed Oil",                "oil",           1409.06, "Cold-pressed organic flaxseed oil, rich in omega-3",                                      1),
        (12,  "Avocado Oil",                         "oil",           1785.06, "Cold-pressed avocado oil, high smoke point",                                              0),
        # ── Nuts & Seeds (4) ──────────────────────────────────────────────────
        (13,  "Organic Almonds",                     "nuts",          1127.06, "Raw organic almonds, unsalted, non-GMO certified",                                        1),
        (14,  "Roasted Cashews",                     "nuts",           939.06, "Lightly salted dry-roasted cashews",                                                      0),
        (15,  "Organic Chia Seeds",                  "seeds",          798.06, "Organic black chia seeds, high in fiber and omega-3",                                     1),
        (16,  "Mixed Nuts",                          "nuts",          1315.06, "Premium mix of walnuts, pecans, almonds and Brazil nuts",                                 0),
        # ── Grains & Cereals (4) ──────────────────────────────────────────────
        (17,  "Organic Quinoa",                      "grains",        1033.06, "Organic white quinoa, complete protein, gluten-free",                                     1),
        (18,  "Rolled Oats",                         "grains",         516.06, "Whole grain rolled oats, great for porridge and baking",                                  0),
        (19,  "Organic Brown Rice",                  "grains",         751.06, "Long-grain organic brown rice, naturally gluten-free",                                    1),
        (20,  "Steel-Cut Oats",                      "grains",         657.06, "Traditional steel-cut oats, low GI, hearty texture",                                     0),
        # ── Tea & Coffee (4) ──────────────────────────────────────────────────
        (21,  "Organic Green Tea",                   "tea",           1221.06, "Japanese organic sencha green tea, 50 bags",                                              1),
        (22,  "Chamomile Tea",                       "tea",            845.06, "Dried chamomile flowers, caffeine-free, soothing",                                        0),
        (23,  "Organic Ethiopian Coffee",            "coffee",        1597.06, "Single-origin organic Arabica, medium roast whole bean",                                  1),
        (24,  "Dark Roast Espresso Blend",           "coffee",        1362.06, "Bold dark roast espresso blend, ground",                                                  0),
        # ── Snacks (4) ────────────────────────────────────────────────────────
        (25,  "Organic Granola",                     "snacks",         939.06, "Organic oat granola with honey, almonds and dried cranberries",                          1),
        (26,  "Rice Cakes",                          "snacks",         422.06, "Lightly salted brown rice cakes, low calorie",                                            0),
        (27,  "Organic Dried Mango",                 "snacks",         751.06, "Unsweetened organic dried mango slices, no preservatives",                                1),
        (28,  "Trail Mix",                           "snacks",         798.06, "Classic trail mix with raisins, M&Ms, peanuts and sunflower seeds",                      0),
        # ── Dairy Alternatives (4) ────────────────────────────────────────────
        (29,  "Organic Almond Milk",                 "dairy-alt",      469.06, "Unsweetened organic almond milk, fortified with calcium",                                 1),
        (30,  "Oat Milk",                            "dairy-alt",      422.06, "Barista-style oat milk, great for coffee",                                                0),
        (31,  "Organic Coconut Milk",                "dairy-alt",      375.06, "Full-fat organic coconut milk, great for curries",                                        1),
        (32,  "Soy Milk",                            "dairy-alt",      328.06, "Unsweetened soy milk, high protein",                                                      0),
        # ── Vegetables (5) ────────────────────────────────────────────────────
        (33,  "Organic Baby Spinach",                "vegetables",     375.06, "Fresh organic baby spinach, tender leaves, rich in iron and vitamins",                   1),
        (34,  "Sweet Bell Peppers Mix",              "vegetables",     422.06, "Colorful mix of red, yellow and orange bell peppers",                                     0),
        (35,  "Organic Broccoli Florets",            "vegetables",     516.06, "Fresh organic broccoli florets, high in vitamin C and fiber",                            1),
        (36,  "Heirloom Cherry Tomatoes",            "vegetables",     469.06, "Juicy heirloom cherry tomatoes, vine-ripened and sweet",                                 0),
        (37,  "Organic Kale",                        "vegetables",     328.06, "Fresh organic curly kale, superfood packed with antioxidants",                           1),
        # ── Fruits (5) ────────────────────────────────────────────────────────
        (38,  "Organic Blueberries",                 "fruits",         657.06, "Fresh organic blueberries, antioxidant-rich and sweet",                                  1),
        (39,  "Organic Strawberries",                "fruits",         563.06, "Plump organic strawberries, no pesticides, picked at peak ripeness",                    1),
        (40,  "Medjool Dates",                       "fruits",         939.06, "Premium Medjool dates from California, soft and caramel-sweet",                          0),
        (41,  "Organic Bananas",                     "fruits",         281.06, "Fair-trade organic bananas, perfectly ripe and naturally sweet",                         1),
        (42,  "Dried Cranberries",                   "fruits",         610.06, "Lightly sweetened dried cranberries, great for baking and salads",                      0),
        # ── Spices & Herbs (5) ────────────────────────────────────────────────
        (43,  "Organic Turmeric Powder",             "spices",         751.06, "Pure organic turmeric powder, high curcumin content, anti-inflammatory",                1),
        (44,  "Smoked Paprika",                      "spices",         516.06, "Spanish smoked paprika, bold and smoky, perfect for meats and stews",                   0),
        (45,  "Organic Cinnamon",                    "spices",         657.06, "Ceylon organic cinnamon, true cinnamon with sweet warm flavor",                         1),
        (46,  "Himalayan Pink Salt",                 "spices",         469.06, "Coarse Himalayan pink salt, mineral-rich and unrefined",                                0),
        (47,  "Organic Cumin Seeds",                 "spices",         563.06, "Whole organic cumin seeds, earthy and aromatic",                                        1),
        # ── Pasta & Noodles (3) ───────────────────────────────────────────────
        (48,  "Organic Whole Wheat Spaghetti",       "pasta",          375.06, "Organic whole wheat spaghetti, high fiber, al dente texture",                           1),
        (49,  "Chickpea Pasta",                      "pasta",          516.06, "Gluten-free chickpea pasta, high protein and rich in fiber",                            0),
        (50,  "Brown Rice Noodles",                  "pasta",          422.06, "Organic brown rice noodles, gluten-free, great for stir-fries",                        1),
        # ── Vinegar & Condiments (2) ──────────────────────────────────────────
        (51,  "Organic Apple Cider Vinegar",         "vinegar",        845.06, "Raw unfiltered organic apple cider vinegar with the mother",                            1),
        (52,  "Balsamic Vinegar of Modena",          "vinegar",       1221.06, "Aged balsamic vinegar of Modena IGP, rich and complex flavor",                         0),
        # ── Beverages (10) ────────────────────────────────────────────────────
        (53,  "Fresh Squeezed Orange Juice",         "beverages",      657.06, "Cold-pressed fresh orange juice, no pulp, no added sugar",                              0),
        (54,  "Organic Apple Juice",                 "beverages",      563.06, "100% pure organic apple juice, no concentrate",                                         1),
        (55,  "Sparkling Water 12-Pack",             "beverages",      845.06, "Natural sparkling water with a hint of lemon, zero calories",                           0),
        (56,  "Coconut Water",                       "beverages",      375.06, "Natural coconut water, great electrolyte source",                                       0),
        (57,  "Organic Green Smoothie Blend",        "beverages",      751.06, "Organic spinach, kale, apple and ginger cold-pressed juice",                            1),
        (58,  "Kombucha Ginger Lemon",               "beverages",      422.06, "Live culture kombucha, tangy and refreshing",                                           0),
        (59,  "Organic Cold Brew Coffee",            "beverages",      939.06, "Smooth organic cold brew coffee, ready to drink",                                       1),
        (60,  "Aloe Vera Juice",                     "beverages",      798.06, "Pure aloe vera juice, soothing and hydrating",                                          0),
        (61,  "Protein Shake Chocolate",             "beverages",      375.06, "Ready-to-drink chocolate protein shake, 20g protein",                                   0),
        (62,  "Elderflower Cordial",                 "beverages",      704.06, "Delicate elderflower cordial, mix with water or sparkling water",                       0),
        # ── Bread & Bakery (8) ────────────────────────────────────────────────
        (63,  "Whole Wheat Sourdough Bread",         "bakery",         657.06, "Artisan whole wheat sourdough with crispy crust and chewy crumb",                       0),
        (64,  "Organic Multigrain Bread",            "bakery",         563.06, "Organic multigrain bread with seeds, high in fiber",                                    1),
        (65,  "Everything Bagels 6-Pack",            "bakery",         422.06, "Classic everything bagels with sesame, poppy and onion",                                0),
        (66,  "Butter Croissants 4-Pack",            "bakery",         563.06, "Flaky all-butter croissants, freshly baked",                                            0),
        (67,  "Rye Bread",                           "bakery",         516.06, "Dense and hearty rye bread, great for sandwiches",                                      0),
        (68,  "Organic Spelt Bread",                 "bakery",         704.06, "Organic spelt bread, easier to digest than wheat",                                      1),
        (69,  "Gluten-Free Sandwich Bread",          "bakery",         657.06, "Soft gluten-free sandwich bread, rice flour based",                                     0),
        (70,  "Whole Wheat Pita Bread 6-Pack",       "bakery",         328.06, "Soft whole wheat pita breads, great for dipping",                                       0),
        # ── Meat & Poultry (8) ────────────────────────────────────────────────
        (71,  "Organic Chicken Breast 1lb",          "meat",          1221.06, "Free-range organic boneless skinless chicken breast",                                    1),
        (72,  "Grass-Fed Ground Beef 1lb",           "meat",          1409.06, "100% grass-fed and grass-finished ground beef, 90% lean",                               1),
        (73,  "Sliced Turkey Breast",                "meat",           939.06, "Deli-style sliced turkey breast, low sodium",                                            0),
        (74,  "Organic Chicken Thighs 1lb",          "meat",          1033.06, "Juicy organic bone-in chicken thighs, free-range",                                      1),
        (75,  "Beef Sirloin Steak 8oz",              "meat",          1785.06, "USDA Choice beef sirloin steak, tender and flavorful",                                   0),
        (76,  "Pork Tenderloin 1lb",                 "meat",          1127.06, "Lean pork tenderloin, great for roasting or grilling",                                   0),
        (77,  "Chicken Sausages 4-Pack",             "meat",           845.06, "Fully cooked chicken sausages, light and flavorful",                                     0),
        (78,  "Lamb Chops 2-Pack",                   "meat",          2161.06, "New Zealand lamb rib chops, tender and juicy",                                           0),
        # ── Seafood (6) ───────────────────────────────────────────────────────
        (79,  "Atlantic Salmon Fillet 6oz",          "seafood",       1409.06, "Fresh Atlantic salmon fillet, rich in omega-3 fatty acids",                             0),
        (80,  "Wild-Caught Tuna Steak 6oz",          "seafood",       1597.06, "Sushi-grade wild-caught yellowfin tuna steak",                                          0),
        (81,  "Large Shrimp 1lb",                    "seafood",       1785.06, "Peeled and deveined large shrimp, ready to cook",                                       0),
        (82,  "Cod Fillet 6oz",                      "seafood",       1221.06, "Fresh Atlantic cod fillet, mild and flaky",                                              0),
        (83,  "Canned Wild Salmon",                  "seafood",        657.06, "Wild-caught Alaskan pink salmon, canned in water",                                       0),
        (84,  "Tilapia Fillet 1lb",                  "seafood",       1127.06, "Fresh farm-raised tilapia fillets, mild white fish",                                     0),
        # ── Dairy (10) ────────────────────────────────────────────────────────
        (85,  "Whole Milk 1 Gallon",                 "dairy",          469.06, "Fresh whole milk, vitamin D fortified",                                                   0),
        (86,  "Organic Whole Milk Half Gallon",      "dairy",          563.06, "Organic pasture-raised whole milk, rBST-free",                                           1),
        (87,  "Sharp Cheddar Cheese Block 8oz",      "dairy",          516.06, "Aged sharp cheddar cheese block, bold flavor",                                           0),
        (88,  "Organic Greek Yogurt 32oz",           "dairy",          751.06, "Thick and creamy organic plain Greek yogurt, 20g protein per cup",                      1),
        (89,  "Salted Butter 4 Sticks",              "dairy",          563.06, "Classic salted butter, great for baking and cooking",                                    0),
        (90,  "Organic Cream Cheese 8oz",            "dairy",          422.06, "Smooth and creamy organic cream cheese",                                                 1),
        (91,  "Parmesan Cheese 6oz",                 "dairy",          704.06, "Finely grated Parmigiano Reggiano, aged 24 months",                                      0),
        (92,  "Free-Range Eggs 12-Count",            "dairy",          563.06, "Large free-range eggs, certified humane",                                                 1),
        (93,  "Fresh Mozzarella 16oz",               "dairy",          610.06, "Fresh whole milk mozzarella, great for pizza and salads",                                0),
        (94,  "Heavy Whipping Cream 1 Pint",         "dairy",          375.06, "Fresh heavy whipping cream, 36% fat, for cooking and desserts",                         0),
        # ── Condiments & Sauces (8) ───────────────────────────────────────────
        (95,  "Organic Ketchup 24oz",                "condiments",     469.06, "Organic tomato ketchup, no high-fructose corn syrup",                                    1),
        (96,  "Dijon Mustard 8oz",                   "condiments",     375.06, "Classic Dijon mustard, sharp and tangy",                                                 0),
        (97,  "Mayonnaise 30oz",                     "condiments",     516.06, "Real creamy mayonnaise made with cage-free eggs",                                        0),
        (98,  "Red Hot Sauce 12oz",                  "condiments",     422.06, "Classic Louisiana-style red hot sauce, cayenne pepper",                                  0),
        (99,  "Low-Sodium Soy Sauce 16oz",           "condiments",     375.06, "Naturally brewed low-sodium soy sauce",                                                  0),
        (100, "Organic BBQ Sauce 18oz",              "condiments",     657.06, "Smoky organic BBQ sauce, no artificial flavors",                                         1),
        (101, "Tahini Sesame Paste 16oz",            "condiments",     845.06, "100% ground sesame tahini, smooth and nutty",                                            0),
        (102, "Sriracha Hot Chili Sauce 17oz",       "condiments",     469.06, "Classic sriracha chili garlic sauce, medium heat",                                       0),
        # ── Canned Goods (8) ──────────────────────────────────────────────────
        (103, "Organic Black Beans 15oz",            "canned",         187.06, "Cooked organic black beans in water, no added salt",                                     1),
        (104, "Diced Tomatoes 14oz",                 "canned",         168.26, "Vine-ripened diced tomatoes, great for sauces and soups",                                0),
        (105, "Chickpeas Garbanzo Beans 15oz",       "canned",         177.66, "Cooked chickpeas in water, ready to use",                                                0),
        (106, "Organic Pumpkin Puree 15oz",          "canned",         328.06, "100% pure organic pumpkin puree, great for pies and soups",                              1),
        (107, "Coconut Cream 13.5oz",                "canned",         281.06, "Rich coconut cream, great for curries and desserts",                                     0),
        (108, "Organic Tomato Sauce 24oz",           "canned",         375.06, "Organic smooth tomato pasta sauce with basil",                                           1),
        (109, "Sweet Corn 15oz",                     "canned",         140.06, "Whole kernel sweet corn, no added salt or sugar",                                        0),
        (110, "Cannellini White Beans 15oz",         "canned",         187.06, "Tender cannellini white beans, perfect for Italian dishes",                              0),
        # ── Breakfast Foods (6) ───────────────────────────────────────────────
        (111, "Organic Pure Maple Syrup 12oz",       "breakfast",     1409.06, "Grade A dark organic maple syrup, robust flavor",                                        1),
        (112, "Whole Grain Pancake Mix 32oz",        "breakfast",      657.06, "Complete whole grain pancake and waffle mix",                                             0),
        (113, "Corn Flakes Cereal 18oz",             "breakfast",      469.06, "Classic corn flakes cereal, lightly sweetened",                                          0),
        (114, "Chewy Granola Bars 6-Pack",           "breakfast",      610.06, "Soft and chewy granola bars with oats and honey",                                        0),
        (115, "Organic Muesli 24oz",                 "breakfast",      845.06, "European-style organic muesli with fruits and nuts",                                     1),
        (116, "Frozen Buttermilk Waffles 8-Pack",    "breakfast",      469.06, "Fluffy frozen waffles, ready in minutes",                                                 0),
        # ── Baking Supplies (6) ───────────────────────────────────────────────
        (117, "All-Purpose Flour 5lb",               "baking",         469.06, "Enriched all-purpose flour, perfect for all baking needs",                               0),
        (118, "Organic Cane Sugar 2lb",              "baking",         422.06, "Unbleached organic cane sugar, minimally processed",                                     1),
        (119, "Baking Powder 8oz",                   "baking",         281.06, "Double-acting baking powder, aluminum-free",                                             0),
        (120, "Pure Vanilla Extract 4oz",            "baking",         845.06, "100% pure Madagascar vanilla extract",                                                   0),
        (121, "Dark Chocolate Chips 12oz",           "baking",         563.06, "60% cacao dark chocolate chips, great for cookies",                                      0),
        (122, "Organic Coconut Flour 16oz",          "baking",         704.06, "Fine organic coconut flour, high fiber, gluten-free",                                    1),
        # ── Legumes (5) ───────────────────────────────────────────────────────
        (123, "Organic Red Lentils 1lb",             "legumes",        375.06, "Split organic red lentils, cook quickly, high protein",                                  1),
        (124, "Green Split Peas 1lb",                "legumes",        281.06, "Dried green split peas, great for hearty soups",                                         0),
        (125, "Organic Mung Beans 1lb",              "legumes",        422.06, "Whole organic mung beans, great sprouted or cooked",                                     1),
        (126, "Pinto Beans 1lb",                     "legumes",        234.06, "Dried pinto beans, great for Mexican dishes",                                             0),
        (127, "Organic Black-Eyed Peas 1lb",         "legumes",        328.06, "Dried organic black-eyed peas, creamy texture when cooked",                              1),
        # ── Chocolate & Sweets (6) ────────────────────────────────────────────
        (128, "70% Dark Chocolate Bar 3.5oz",        "chocolate",      469.06, "Fine dark chocolate 70% cacao, smooth and intense",                                      0),
        (129, "Organic Milk Chocolate Bar 3.5oz",    "chocolate",      516.06, "Creamy organic milk chocolate bar, ethically sourced cocoa",                             1),
        (130, "White Chocolate Chips 10oz",          "chocolate",      422.06, "Premium white chocolate chips for baking",                                                0),
        (131, "Organic Cacao Powder 8oz",            "chocolate",      939.06, "Raw organic cacao powder, rich in antioxidants",                                         1),
        (132, "Dark Chocolate Almonds 8oz",          "chocolate",      845.06, "Roasted almonds enrobed in dark chocolate",                                               0),
        (133, "Gummy Bears 14oz",                    "chocolate",      422.06, "Classic fruit-flavored gummy bears, assorted flavors",                                   0),
        # ── Spreads & Jams (6) ────────────────────────────────────────────────
        (134, "Natural Peanut Butter 16oz",          "spreads",        657.06, "Creamy natural peanut butter, just peanuts and salt",                                    0),
        (135, "Organic Almond Butter 16oz",          "spreads",       1221.06, "Smooth organic almond butter, no added sugar or oil",                                    1),
        (136, "Strawberry Jam 18oz",                 "spreads",        469.06, "Classic strawberry jam made with real fruit",                                             0),
        (137, "Organic Raspberry Preserves 10oz",   "spreads",        657.06, "Organic seedless raspberry preserves, fruit-forward flavor",                             1),
        (138, "Hazelnut Chocolate Spread 13oz",      "spreads",        563.06, "Creamy hazelnut and cocoa spread, great on toast",                                       0),
        (139, "Sunflower Seed Butter 16oz",          "spreads",        939.06, "Creamy sunflower seed butter, nut-free and allergy-friendly",                           0),
        # ── Soups & Broths (5) ────────────────────────────────────────────────
        (140, "Organic Chicken Broth 32oz",          "soups",          469.06, "Low-sodium organic chicken broth, slow-simmered",                                        1),
        (141, "Vegetable Broth 32oz",                "soups",          375.06, "Rich vegetable broth, great for soups and risottos",                                     0),
        (142, "Organic Tomato Basil Soup 24oz",      "soups",          422.06, "Creamy organic tomato basil soup, restaurant quality",                                   1),
        (143, "Ready-to-Eat Lentil Soup 18oz",       "soups",          375.06, "Hearty lentil soup with vegetables, no preservatives",                                   0),
        (144, "Bone Broth Chicken 24oz",             "soups",          845.06, "Slow-simmered chicken bone broth, high in collagen and protein",                        0),
        # ── Chips & Crackers (6) ──────────────────────────────────────────────
        (145, "Organic Tortilla Chips 9oz",          "chips",          469.06, "Organic yellow corn tortilla chips, lightly salted",                                     1),
        (146, "Kettle Cooked Sea Salt Chips 8oz",    "chips",          422.06, "Crunchy kettle-cooked potato chips with sea salt",                                       0),
        (147, "Brown Rice Crackers 4oz",             "chips",          328.06, "Light and crunchy brown rice crackers, gluten-free",                                     0),
        (148, "Whole Grain Pretzels 10oz",           "chips",          375.06, "Crunchy whole grain pretzel twists, lightly salted",                                     0),
        (149, "Pita Chips Original 8oz",             "chips",          422.06, "Baked pita chips, great with hummus and dips",                                           0),
        (150, "Cassava Flour Tortilla Chips 8oz",    "chips",          563.06, "Grain-free cassava tortilla chips, paleo friendly",                                      1),
        # ── Health Supplements (5) ────────────────────────────────────────────
        (151, "Organic Whey Protein Powder 2lb",     "supplements",   4229.06, "Organic grass-fed whey protein, chocolate flavor, 25g protein per serving",             1),
        (152, "Vitamin D3 Drops 1oz",                "supplements",   1409.06, "Liquid vitamin D3 drops, 2000 IU per serving",                                           0),
        (153, "Organic Ashwagandha Powder 8oz",      "supplements",   1879.06, "Organic adaptogenic ashwagandha root powder, stress relief",                            1),
        (154, "Fish Oil Omega-3 60 Softgels",        "supplements",   1597.06, "High-potency fish oil softgels, 1200mg EPA+DHA",                                        0),
        (155, "Organic Spirulina Powder 8oz",        "supplements",   2161.06, "Certified organic blue-green spirulina, nutrient-dense superfood",                      1),
        # ── Frozen Foods (8) ──────────────────────────────────────────────────
        (156, "Organic Frozen Peas 16oz",            "frozen",         375.06, "Sweet organic peas, flash-frozen to preserve nutrition",                                  1),
        (157, "Frozen Mixed Berries 32oz",           "frozen",         845.06, "Blend of strawberries, blueberries and raspberries",                                     0),
        (158, "Organic Frozen Edamame 16oz",         "frozen",         469.06, "Ready-to-eat organic edamame, lightly salted",                                           1),
        (159, "Frozen Broccoli Florets 16oz",        "frozen",         281.06, "Flash-frozen broccoli florets, great for stir-fries",                                    0),
        (160, "Frozen Cauliflower Rice 12oz",        "frozen",         422.06, "Ready-to-cook cauliflower rice, low-carb alternative",                                   0),
        (161, "Organic Frozen Corn 16oz",            "frozen",         328.06, "Sweet organic frozen corn kernels, no additives",                                        1),
        (162, "Veggie Burger Patties 4-Pack",        "frozen",         845.06, "Plant-based veggie burger patties, high in protein",                                     0),
        (163, "Organic Frozen Waffles 8-Pack",       "frozen",         610.06, "Organic whole grain frozen waffles, lightly sweetened",                                  1),
        # ── Baby Food (4) ─────────────────────────────────────────────────────
        (164, "Organic Baby Pea & Spinach Puree",    "baby",           234.06, "Organic stage 2 baby food puree, peas and spinach blend",                               1),
        (165, "Organic Baby Oatmeal Cereal 8oz",     "baby",           657.06, "Organic iron-fortified baby oatmeal, smooth texture",                                   1),
        (166, "Sweet Potato Baby Puree 4oz",         "baby",           187.06, "Smooth sweet potato puree, no added sugar or salt",                                     0),
        (167, "Organic Baby Teething Crackers",      "baby",           563.06, "Organic rice-based teething crackers, dissolves safely",                                 1),
        # ── Deli & Prepared Foods (6) ─────────────────────────────────────────
        (168, "Classic Hummus 10oz",                 "deli",           469.06, "Smooth and creamy classic hummus with olive oil drizzle",                                0),
        (169, "Organic Guacamole 8oz",               "deli",           563.06, "Fresh organic guacamole with lime and cilantro",                                         1),
        (170, "Greek Tzatziki Dip 12oz",             "deli",           516.06, "Creamy Greek yogurt tzatziki with cucumber and dill",                                    0),
        (171, "Marinated Chicken Kebabs 1lb",        "deli",          1221.06, "Pre-marinated Mediterranean chicken kebabs, grill-ready",                                0),
        (172, "Organic Salsa Medium 16oz",           "deli",           563.06, "Chunky organic medium salsa with tomatoes and jalapeños",                                1),
        (173, "Smoked Salmon Cream Cheese 6oz",      "deli",           845.06, "Whipped cream cheese blended with smoked Atlantic salmon",                               0),
        # ── Protein Bars (5) ──────────────────────────────────────────────────
        (174, "Clif Bar Chocolate Chip 6-Pack",      "protein-bars",  1033.06, "Energy bars with organic oats and chocolate chips",                                      0),
        (175, "Kind Bar Almond Coconut 12-Pack",     "protein-bars",  1879.06, "Whole nut and fruit bars with almond and toasted coconut",                               0),
        (176, "Organic Larabar 8-Pack",              "protein-bars",  1409.06, "Organic fruit and nut bars, minimal ingredients",                                        1),
        (177, "Quest Bar Cookies & Cream 4-Pack",    "protein-bars",  1127.06, "High-protein bars with 21g protein and low sugar",                                       0),
        (178, "RXBAR Chocolate Sea Salt 12-Pack",    "protein-bars",  2537.06, "Clean protein bars, whole food ingredients, 12g protein",                                0),
        # ── Fresh Herbs (4) ───────────────────────────────────────────────────
        (179, "Fresh Basil 1oz",                     "herbs",          281.06, "Fresh sweet basil, perfect for pesto and Italian cooking",                               0),
        (180, "Organic Fresh Mint 1oz",              "herbs",          234.06, "Fresh organic spearmint, great for teas and garnishes",                                  1),
        (181, "Fresh Cilantro 1oz",                  "herbs",          187.06, "Bright fresh cilantro, essential for Mexican and Asian cooking",                         0),
        (182, "Organic Fresh Rosemary 1oz",          "herbs",          281.06, "Fresh organic rosemary sprigs, great for roasting",                                      1),
        # ── Jams & Preserves (4) ──────────────────────────────────────────────
        (183, "Blueberry Jam 18oz",                  "jams",           516.06, "Rich blueberry jam made with real fruit, no artificial flavors",                        0),
        (184, "Organic Apricot Preserves 12oz",      "jams",           657.06, "Chunky organic apricot preserves, made with whole fruit",                               1),
        (185, "Orange Marmalade 12oz",               "jams",           469.06, "Classic orange marmalade with real peel, bittersweet",                                   0),
        (186, "Organic Fig Jam 10oz",                "jams",           751.06, "Thick organic fig jam, perfect with cheese and crackers",                                1),
        # ── More Tea & Coffee (7) ─────────────────────────────────────────────
        (187, "Organic Matcha Powder 3oz",           "tea",           1785.06, "Ceremonial grade organic matcha green tea powder from Japan",                            1),
        (188, "Yerba Mate 1lb",                      "tea",           1409.06, "Traditional Argentinian yerba mate loose leaf, energizing",                              0),
        (189, "Hibiscus Herbal Tea 20 Bags",         "tea",            751.06, "Tart and floral hibiscus tea, naturally caffeine-free",                                  0),
        (190, "Organic Golden Milk Turmeric Mix 8oz","tea",           1221.06, "Organic turmeric-ginger golden milk blend, just add milk",                               1),
        (191, "Decaf Colombian Coffee 12oz",         "coffee",        1315.06, "Swiss water decaf Colombian coffee, medium roast",                                       0),
        (192, "Hazelnut Flavored Ground Coffee 12oz","coffee",        1174.06, "Smooth medium roast with natural hazelnut flavor",                                       0),
        (193, "Organic Mushroom Coffee Blend 8oz",   "coffee",        2349.06, "Organic coffee blended with lion's mane and chaga mushrooms",                            1),
        # ── More Pasta & Grains (13) ──────────────────────────────────────────
        (194, "Orzo Pasta 16oz",                     "pasta",          281.06, "Rice-shaped orzo pasta, great for soups and salads",                                     0),
        (195, "Red Lentil Pasta 8oz",                "pasta",          469.06, "High-protein gluten-free pasta made from red lentils",                                   0),
        (196, "Organic Farro 16oz",                  "grains",         657.06, "Ancient whole grain farro, nutty flavor and chewy texture",                              1),
        (197, "Amaranth 16oz",                       "grains",         563.06, "Tiny ancient grain amaranth, gluten-free and protein-rich",                              0),
        (198, "Organic Millet 16oz",                 "grains",         469.06, "Hulled organic millet, mild flavor, great alternative to rice",                         1),
        (199, "Pearl Couscous 16oz",                 "grains",         328.06, "Large pearl couscous, toasted wheat, great for salads",                                  0),
        (200, "Organic Buckwheat Groats 16oz",       "grains",         516.06, "Roasted organic buckwheat groats (kasha), nutty and earthy",                             1),
        (201, "Long Grain White Rice 5lb",           "grains",         751.06, "Extra-long grain enriched white rice, fluffy when cooked",                               0),
        (202, "Jasmine Rice 5lb",                    "grains",         845.06, "Thai jasmine rice, fragrant and slightly sticky",                                         0),
        (203, "Basmati Rice 5lb",                    "grains",         939.06, "Aged Indian basmati rice, long-grain and aromatic",                                      0),
        (204, "Polenta Cornmeal 24oz",               "grains",         422.06, "Stone-ground yellow cornmeal for polenta and baking",                                    0),
        (205, "Organic Teff Flour 16oz",             "grains",         563.06, "Ancient Ethiopian grain teff flour, high in iron and calcium",                          1),
        # ── More Nuts & Seeds (6) ─────────────────────────────────────────────
        (206, "Organic Walnuts 8oz",                 "nuts",          1033.06, "Raw organic walnut halves, rich in omega-3 and antioxidants",                           1),
        (207, "Pumpkin Seeds Pepitas 8oz",           "seeds",          751.06, "Roasted and lightly salted pumpkin seeds, great snack",                                  0),
        (208, "Organic Sunflower Seeds 8oz",         "seeds",          469.06, "Organic dry-roasted sunflower seeds, unsalted",                                          1),
        (209, "Organic Flaxseeds 16oz",              "seeds",          516.06, "Whole organic flaxseeds, rich in omega-3 and lignans",                                   1),
        (210, "Macadamia Nuts 6oz",                  "nuts",          1409.06, "Premium Hawaiian macadamia nuts, buttery and rich",                                      0),
        (211, "Organic Pecans 8oz",                  "nuts",          1221.06, "Raw organic pecan halves, sweet and buttery",                                            1),
    ]

    cursor.executemany("INSERT OR REPLACE INTO products VALUES (?, ?, ?, ?, ?, ?)", products)

    reviews = [
        # ── Honey ─────────────────────────────────────────────────────────────
        (1,   5.0, "Alice",    "Amazing honey! Best I've ever tried."),
        (1,   4.0, "Bob",      "Good quality, will buy again."),
        (1,   5.0, "Carol",    "Excellent raw flavor, very pure."),
        (1,   4.5, "Dave",     "Very good, love that it's unfiltered."),
        (2,   4.0, "Eve",      "Decent honey for the price."),
        (2,   3.5, "Frank",    "Average, nothing special."),
        (2,   4.0, "Grace",    "Good everyday honey."),
        (3,   5.0, "Henry",    "Worth every penny, incredible quality."),
        (3,   4.5, "Iris",     "Excellent antibacterial properties."),
        (3,   5.0, "Jack",     "Best honey I have ever tasted."),
        (4,   3.5, "Kate",     "Okay for cooking, nothing fancy."),
        (4,   3.5, "Leo",      "Nothing special, pretty generic."),
        (4,   3.5, "Mia",      "Average clover honey."),
        (5,   5.0, "Noah",     "Rich bold flavor, great in tea."),
        (5,   4.0, "Olivia",   "Good strong honey, unique taste."),
        (5,   5.0, "Paul",     "Love the dark color and depth."),
        (5,   4.5, "Quinn",    "Great organic option at this price."),
        (6,   4.0, "Rachel",   "Nice floral flavor."),
        (6,   4.5, "Sam",      "Lovely and delicate."),
        (6,   4.0, "Tina",     "Good for baking."),
        (7,   5.0, "Uma",      "Perfect mild flavor, love it!"),
        (7,   4.5, "Victor",   "Excellent light honey."),
        (7,   4.5, "Wendy",    "Great product, very pure taste."),
        (7,   5.0, "Xavier",   "Wonderful, highly recommend."),
        (8,   4.0, "Yvonne",   "Nice spreadable texture."),
        (8,   4.0, "Zack",     "Good on toast."),
        (8,   4.0, "Amy",      "Decent creamed honey."),
        # ── Oils ──────────────────────────────────────────────────────────────
        (9,   5.0, "Brian",    "Best olive oil I've used, very fresh."),
        (9,   4.5, "Clara",    "Great flavor, organic certified."),
        (9,   4.5, "Derek",    "Excellent quality, love it."),
        (10,  4.0, "Elena",    "Good for frying, neutral taste."),
        (10,  3.5, "Felix",    "Does the job, nothing exciting."),
        (10,  3.5, "Gina",     "Decent but slightly greasy."),
        (11,  5.0, "Harry",    "Great for smoothies, very fresh."),
        (11,  4.0, "Isla",     "Good omega-3 source, mild flavor."),
        (11,  4.5, "James",    "Love this for salad dressings."),
        (12,  4.5, "Karen",    "Excellent smoke point, tastes great."),
        (12,  4.0, "Liam",     "Good all-purpose oil."),
        (12,  4.5, "Maya",     "Great for cooking and salads."),
        # ── Nuts & Seeds ──────────────────────────────────────────────────────
        (13,  5.0, "Nate",     "Crunchy and fresh, great snack."),
        (13,  4.5, "Olivia",   "Love that they're organic and raw."),
        (13,  4.5, "Peter",    "Perfect size, very fresh."),
        (13,  5.0, "Rita",     "Best almonds I've bought online."),
        (14,  4.0, "Steve",    "Good cashews, nice crunch."),
        (14,  4.0, "Tara",     "Tasty but slightly over-salted."),
        (14,  4.0, "Ursula",   "Good value for the quantity."),
        (15,  4.5, "Vince",    "Easy to add to smoothies, love it."),
        (15,  4.5, "Wanda",    "Great fiber source, very fresh."),
        (15,  4.5, "Xena",     "Good quality organic chia seeds."),
        (16,  4.0, "Yuri",     "Good mix, well-balanced variety."),
        (16,  3.5, "Zara",     "A bit too many peanuts for my taste."),
        (16,  4.0, "Alex",     "Nice mix for snacking."),
        (16,  3.5, "Blake",    "Would prefer fewer raisins."),
        # ── Grains ────────────────────────────────────────────────────────────
        (17,  5.0, "Chloe",    "Cooks perfectly, great nutty flavor."),
        (17,  4.5, "Dylan",    "Excellent protein content, love it."),
        (17,  4.5, "Ella",     "Best quinoa I've tried."),
        (18,  4.5, "Finn",     "Great oats, cook quickly and evenly."),
        (18,  4.0, "Gabi",     "Good quality, nice texture."),
        (18,  4.5, "Hugo",     "Reliable everyday oats."),
        (19,  4.5, "Irene",    "Nice chewy texture, great organic choice."),
        (19,  4.5, "Jake",     "Good quality, cooks evenly."),
        (19,  4.5, "Kara",     "Love the organic certification."),
        (20,  4.0, "Lars",     "Great texture, a bit longer to cook."),
        (20,  3.5, "Mona",     "Takes forever to cook but tastes good."),
        (20,  4.0, "Ned",      "Hearty and filling."),
        # ── Tea & Coffee ──────────────────────────────────────────────────────
        (21,  5.0, "Opal",     "Delicate flavor, very smooth."),
        (21,  4.5, "Phil",     "Best green tea I've had, very fresh."),
        (21,  4.5, "Quinn",    "Great quality, calming and tasty."),
        (22,  4.0, "Rose",     "Very soothing before bed."),
        (22,  4.5, "Seth",     "Lovely floral notes, very relaxing."),
        (22,  4.0, "Tess",     "Good chamomile, nice and mild."),
        (23,  5.0, "Uri",      "Best coffee I've ever brewed at home."),
        (23,  4.5, "Vera",     "Amazing single-origin flavor."),
        (23,  4.5, "Will",     "Very smooth with great aroma."),
        (23,  5.0, "Xara",     "Exceptional quality, worth every penny."),
        (24,  4.0, "Yael",     "Strong and bold, perfect espresso."),
        (24,  4.0, "Zion",     "Good dark roast, consistent grind."),
        (24,  4.0, "Abe",      "Solid everyday espresso blend."),
        # ── Snacks ────────────────────────────────────────────────────────────
        (25,  4.5, "Beth",     "Delicious and not too sweet."),
        (25,  4.5, "Cole",     "Great texture, love the almonds."),
        (25,  4.5, "Dana",     "My go-to breakfast granola."),
        (26,  4.0, "Earl",     "Light and crispy, good for dieting."),
        (26,  3.5, "Faye",     "A bit bland but does the job."),
        (26,  4.0, "Glen",     "Good value, decent snack."),
        (27,  5.0, "Hope",     "So sweet and chewy, love these!"),
        (27,  4.5, "Ivan",     "Great that there's no added sugar."),
        (27,  4.5, "Jade",     "Perfect snack, very natural taste."),
        (28,  4.0, "Kent",     "Good mix, great for hiking."),
        (28,  3.5, "Luna",     "Too many M&Ms, prefer less candy."),
        (28,  3.5, "Marc",     "Decent but not my favorite mix."),
        # ── Dairy Alternatives ────────────────────────────────────────────────
        (29,  4.5, "Nina",     "Great in coffee, smooth texture."),
        (29,  4.5, "Omar",     "Love the organic certification."),
        (29,  4.5, "Pam",      "Tastes great and not too thin."),
        (30,  4.5, "Rex",      "Perfect for lattes, froths well."),
        (30,  4.0, "Sara",     "Good oat milk, slightly sweet."),
        (30,  4.5, "Tom",      "Best barista oat milk I've tried."),
        (31,  4.5, "Una",      "Creamy and rich, great for curries."),
        (31,  4.5, "Vito",     "Full fat and delicious."),
        (31,  4.5, "Wren",     "Perfect coconut milk, great quality."),
        (32,  4.0, "Xio",      "Good protein content, mild flavor."),
        (32,  3.5, "Yosef",    "Slightly thin but good for cereal."),
        (32,  3.5, "Zola",     "Decent soy milk, nothing special."),
        # ── Vegetables ────────────────────────────────────────────────────────
        (33,  5.0, "Aiden",    "So fresh and tender, great for salads."),
        (33,  4.5, "Bella",    "Love the organic quality, very clean."),
        (33,  4.5, "Carlos",   "Perfect spinach, arrives very fresh."),
        (34,  4.5, "Diana",    "Beautiful colors and sweet flavor."),
        (34,  4.0, "Ethan",    "Good peppers, slightly smaller than expected."),
        (34,  4.5, "Fiona",    "Great for stir-fries and salads."),
        (35,  5.0, "George",   "Crispy and fresh, excellent organic broccoli."),
        (35,  4.5, "Hannah",   "Very fresh and great quality."),
        (35,  5.0, "Ian",      "Best broccoli I've ordered, very tender."),
        (36,  4.5, "Julia",    "Incredibly sweet, perfect for salads."),
        (36,  4.5, "Kevin",    "Love the heirloom variety, burst of flavor."),
        (36,  4.5, "Laura",    "Juicy and colorful, great product."),
        (37,  4.5, "Mike",     "Super fresh kale, great for smoothies."),
        (37,  4.5, "Nancy",    "Excellent organic kale, very curly and fresh."),
        (37,  4.5, "Oscar",    "Perfect for kale chips and salads."),
        # ── Fruits ────────────────────────────────────────────────────────────
        (38,  5.0, "Paula",    "Sweetest blueberries I've ever tasted!"),
        (38,  4.5, "Quentin",  "Organic and so fresh, love them."),
        (38,  5.0, "Rita",     "Perfect size and flavor, great for smoothies."),
        (39,  5.0, "Simon",    "Incredibly fresh and sweet strawberries."),
        (39,  4.5, "Tracy",    "Great organic quality, no pesticides."),
        (39,  4.5, "Ulrich",   "Wonderful flavor, love the organic certification."),
        (40,  4.5, "Vivian",   "So soft and caramel-sweet, addictive!"),
        (40,  4.5, "Walter",   "Best Medjool dates I've tried, very fresh."),
        (40,  4.5, "Xara",     "Amazing quality, will always buy these."),
        (41,  4.5, "Yasmin",   "Perfectly ripe and sweet, great value."),
        (41,  4.0, "Zane",     "Good bananas, consistent ripeness."),
        (41,  4.5, "Amara",    "Love the fair-trade organic certification."),
        (42,  4.0, "Bruno",    "Nice and tangy, great for oatmeal."),
        (42,  4.0, "Celia",    "Good quality, not too sweet."),
        (42,  4.0, "Devon",    "Good cranberries, slightly more sugar than expected."),
        # ── Spices ────────────────────────────────────────────────────────────
        (43,  5.0, "Elena",    "Vibrant color and powerful flavor, very fresh."),
        (43,  4.5, "Fabian",   "Great organic turmeric, strong and aromatic."),
        (43,  4.5, "Greta",    "Love the high curcumin content, excellent quality."),
        (44,  4.5, "Hector",   "Amazing smoky flavor, transformed my cooking!"),
        (44,  4.0, "Ingrid",   "Good paprika, nice and smoky."),
        (44,  4.5, "Jorge",    "Excellent depth of flavor, perfect for BBQ."),
        (45,  5.0, "Kira",     "True Ceylon cinnamon, completely different from regular!"),
        (45,  5.0, "Leon",     "Incredible warm flavor, best cinnamon I've used."),
        (45,  4.5, "Marta",    "Wonderful aroma, love the organic quality."),
        (46,  4.0, "Nilo",     "Nice mineral taste, good for everyday use."),
        (46,  4.0, "Odette",   "Great pink salt, love the coarse grind."),
        (46,  4.5, "Pedro",    "Beautiful color and clean mineral flavor."),
        (47,  4.5, "Quinn",    "Fresh and aromatic, perfect for Indian cooking."),
        (47,  4.5, "Rosa",     "Excellent whole cumin, very fragrant."),
        (47,  4.5, "Soren",    "Love that they're organic, great flavor."),
        # ── Pasta ─────────────────────────────────────────────────────────────
        (48,  4.5, "Tilda",    "Great whole wheat pasta, nutty and firm."),
        (48,  4.5, "Ugo",      "Good al dente texture, love the organic certification."),
        (48,  4.5, "Vera",     "Excellent whole wheat spaghetti, very filling."),
        (49,  4.5, "Wayne",    "Love the protein content, tastes great too."),
        (49,  4.0, "Xena",     "Good gluten-free option, holds texture well."),
        (49,  4.5, "Yolanda",  "Great chickpea pasta, better than expected."),
        (50,  4.0, "Zach",     "Good for stir-fries, nice neutral flavor."),
        (50,  4.0, "Aisha",    "Decent rice noodles, cooks quickly."),
        (50,  4.5, "Boris",    "Love the gluten-free organic option."),
        # ── Vinegar ───────────────────────────────────────────────────────────
        (51,  5.0, "Cara",     "The mother is clearly visible, very raw and authentic."),
        (51,  4.5, "Dario",    "Great ACV, noticeable health benefits."),
        (51,  4.5, "Elise",    "Perfect for salad dressings and detox drinks."),
        (52,  4.5, "Fabio",    "Rich and complex, incredible depth of flavor."),
        (52,  4.5, "Giulia",   "Authentic Modena balsamic, worth every penny."),
        (52,  4.5, "Hamid",    "Excellent aged balsamic, great for finishing dishes."),
        # ── Beverages ─────────────────────────────────────────────────────────
        (53,  5.0, "Ingrid",   "So fresh and pulpy, feels like home-squeezed."),
        (53,  4.5, "Jake",     "Amazing flavor, great quality."),
        (53,  4.0, "Kimi",     "Good OJ, wish the bottle was bigger."),
        (54,  4.5, "Lena",     "Pure apple taste, not too sweet."),
        (54,  4.5, "Mason",    "Great for the kids, no weird aftertaste."),
        (54,  5.0, "Nadia",    "Best apple juice I've tried, so clean and fresh."),
        (55,  4.5, "Oliver",   "Great value for 12 cans, refreshing."),
        (55,  4.0, "Priya",    "Good sparkling water, subtle lemon flavor."),
        (55,  4.5, "Raj",      "Perfect replacement for soda."),
        (56,  4.5, "Sophie",   "Incredible hydration, love the natural sweetness."),
        (56,  4.0, "Tom",      "Great electrolyte drink post-workout."),
        (56,  5.0, "Uma",      "Pure and natural, much better than sports drinks."),
        (57,  5.0, "Victor",   "Packed with greens and tastes amazing!"),
        (57,  4.5, "Wendy",    "Great for a morning health boost."),
        (57,  4.0, "Xander",   "A bit pricey but excellent quality."),
        (58,  4.5, "Yuki",     "Tangy and fizzy, great gut health drink."),
        (58,  4.0, "Zara",     "Good kombucha, very refreshing."),
        (58,  4.5, "Aaron",    "Love the ginger kick, very authentic."),
        (59,  5.0, "Bianca",   "Smooth and rich, perfect cold coffee."),
        (59,  4.5, "Calvin",   "Great organic cold brew, not too bitter."),
        (59,  4.5, "Daisy",    "My morning ritual, absolutely love it."),
        (60,  4.0, "Edgar",    "Soothing and mild, very hydrating."),
        (60,  3.5, "Fatima",   "A bit bland for my taste but healthy."),
        (60,  4.0, "George",   "Good aloe juice, calming on the stomach."),
        (61,  4.0, "Hannah",   "Decent protein shake, chocolate flavor is good."),
        (61,  3.5, "Igor",     "Okay taste, good for post-workout."),
        (61,  4.0, "Jade",     "Convenient and tasty, solid protein source."),
        (62,  4.5, "Karl",     "Lovely floral flavor, great with sparkling water."),
        (62,  4.0, "Lila",     "Delicate and unique, very British!"),
        (62,  4.5, "Marco",    "Absolutely delightful cordial, very refined."),
        # ── Bakery ────────────────────────────────────────────────────────────
        (63,  5.0, "Nina",     "Crusty outside, chewy inside, perfect sourdough!"),
        (63,  4.5, "Oscar",    "Amazing flavor, real sourdough tang."),
        (63,  4.5, "Paula",    "Best bread I've ordered online."),
        (64,  4.5, "Quinn",    "Hearty and nutritious, love the seeds."),
        (64,  4.0, "Ryan",     "Good organic bread, stays fresh well."),
        (64,  4.5, "Sarah",    "Great texture and flavor for multigrain."),
        (65,  4.5, "Tyler",    "Perfect bagels, great everything topping."),
        (65,  4.0, "Ursula",   "Good size and flavor, great toasted."),
        (65,  4.5, "Vera",     "Classic everything bagels, love them!"),
        (66,  5.0, "Will",     "Buttery and flaky, absolutely divine!"),
        (66,  4.5, "Xena",     "Best croissants I've had outside a bakery."),
        (66,  5.0, "Yael",     "Perfect texture, melt in your mouth goodness."),
        (67,  4.0, "Zach",     "Dense and hearty, great with cream cheese."),
        (67,  4.0, "Abby",     "Classic rye bread, exactly what I wanted."),
        (67,  3.5, "Ben",      "Good but a bit dry."),
        (68,  4.5, "Cara",     "Easier to digest than wheat, great organic."),
        (68,  4.5, "Dan",      "Love the nutty spelt flavor."),
        (68,  4.0, "Ellie",    "Good organic bread, slightly dense but tasty."),
        (69,  4.0, "Fred",     "Good gluten-free bread, holds together well."),
        (69,  3.5, "Grace",    "Decent GF bread but a bit crumbly."),
        (69,  4.0, "Henry",    "Best gluten-free bread I've tried, great texture."),
        (70,  4.5, "Isla",     "Perfect soft pitas, great with hummus."),
        (70,  4.0, "Jake",     "Good whole wheat pitas, healthy and tasty."),
        (70,  4.5, "Kim",      "Fresh and soft, love whole wheat pitas."),
        # ── Meat & Poultry ────────────────────────────────────────────────────
        (71,  5.0, "Leo",      "So tender and juicy, clearly high quality organic."),
        (71,  4.5, "Mia",      "Great free-range chicken, no rubbery texture."),
        (71,  4.5, "Ned",      "Best chicken breast I've bought, very fresh."),
        (72,  5.0, "Olivia",   "Incredible grass-fed beef, tastes so much better."),
        (72,  4.5, "Pete",     "Rich flavor, you can really taste the difference."),
        (72,  5.0, "Quinn",    "Best ground beef, makes amazing burgers."),
        (73,  4.0, "Rose",     "Good deli turkey, nice and lean."),
        (73,  4.0, "Sam",      "Decent sliced turkey, good for sandwiches."),
        (73,  3.5, "Tina",     "A bit processed but fine for everyday use."),
        (74,  4.5, "Uma",      "Juicy and flavorful, great organic quality."),
        (74,  4.5, "Vic",      "Much better than conventional chicken thighs."),
        (74,  4.0, "Will",     "Good organic chicken, great for meal prep."),
        (75,  5.0, "Xara",     "Perfectly marbled, cooked beautifully."),
        (75,  4.5, "Yael",     "Great steak, tender and full of flavor."),
        (75,  4.5, "Zach",     "Excellent quality USDA choice, will buy again."),
        (76,  4.5, "Amy",      "Super lean and tender, cooked perfectly."),
        (76,  4.0, "Bob",      "Good pork tenderloin, versatile cut."),
        (76,  4.5, "Cara",     "Excellent quality, great for weeknight dinners."),
        (77,  4.5, "Dave",     "Tasty chicken sausages, not too greasy."),
        (77,  4.0, "Eve",      "Good flavor, great for a lighter sausage option."),
        (77,  4.0, "Frank",    "Decent sausages, kids love them."),
        (78,  5.0, "Grace",    "Incredibly tender lamb, fell off the bone."),
        (78,  4.5, "Henry",    "Amazing quality New Zealand lamb."),
        (78,  5.0, "Iris",     "Best lamb chops I've ever had at home."),
        # ── Seafood ───────────────────────────────────────────────────────────
        (79,  5.0, "Jake",     "So fresh, cooked perfectly, great omega-3 source."),
        (79,  4.5, "Kim",      "Excellent Atlantic salmon, great color and flavor."),
        (79,  4.5, "Leo",      "Buttery and rich, just like from a restaurant."),
        (80,  5.0, "Mia",      "Sushi-grade quality, melts in your mouth."),
        (80,  4.5, "Ned",      "Fresh and meaty, great grilled."),
        (80,  4.0, "Olivia",   "Good wild-caught tuna, great quality."),
        (81,  4.5, "Pete",     "Perfectly cleaned and deveined, great for stir-fry."),
        (81,  4.0, "Quinn",    "Good large shrimp, cooks quickly."),
        (81,  4.5, "Rose",     "Juicy and sweet shrimp, love these."),
        (82,  4.5, "Sam",      "Flaky and mild, perfect for fish tacos."),
        (82,  4.0, "Tina",     "Good cod fillet, nice and fresh."),
        (82,  4.0, "Uma",      "Decent cod, good value for the price."),
        (83,  4.0, "Victor",   "Great for quick meals, good wild-caught salmon."),
        (83,  4.5, "Will",     "Convenient and healthy, great in salads."),
        (83,  4.0, "Xena",     "Good canned salmon, much better than tuna."),
        (84,  4.0, "Yael",     "Mild and versatile, great everyday fish."),
        (84,  4.5, "Zach",     "Fresh and clean, great for meal prep."),
        (84,  3.5, "Amy",      "Decent tilapia, a bit bland on its own."),
        # ── Dairy ─────────────────────────────────────────────────────────────
        (85,  4.5, "Bob",      "Fresh whole milk, love the richness."),
        (85,  4.0, "Cara",     "Good quality milk, always reliable."),
        (85,  4.5, "Dave",     "Great tasting whole milk, kids love it."),
        (86,  5.0, "Eve",      "Best organic milk, you can taste the quality."),
        (86,  4.5, "Frank",    "Great pasture-raised milk, very fresh."),
        (86,  5.0, "Grace",    "Worth the extra cost, excellent organic milk."),
        (87,  4.5, "Henry",    "Sharp and bold, great on crackers."),
        (87,  5.0, "Iris",     "Best cheddar I've bought in a long time."),
        (87,  4.5, "Jake",     "Great aged cheddar, perfect for grilled cheese."),
        (88,  5.0, "Kim",      "So thick and creamy, excellent protein source."),
        (88,  4.5, "Leo",      "Best Greek yogurt, love the organic quality."),
        (88,  5.0, "Mia",      "Perfect protein breakfast, no sugar added."),
        (89,  4.5, "Ned",      "Classic butter, great for all cooking."),
        (89,  4.0, "Olivia",   "Good butter, consistent quality."),
        (89,  4.5, "Pete",     "Great taste, love for baking."),
        (90,  5.0, "Quinn",    "Smooth and creamy, great organic quality."),
        (90,  4.5, "Rose",     "Perfect on bagels, love the organic certification."),
        (90,  4.5, "Sam",      "Best cream cheese, excellent texture."),
        (91,  5.0, "Tina",     "Authentic Parmigiano Reggiano, incredible flavor."),
        (91,  4.5, "Uma",      "Great parmesan, elevates every dish."),
        (91,  4.5, "Victor",   "Love the aged 24 months version, so rich."),
        (92,  5.0, "Will",     "Beautiful orange yolks, clearly pasture-raised."),
        (92,  4.5, "Xena",     "Great free-range eggs, taste the difference."),
        (92,  5.0, "Yael",     "Best eggs I've had, very fresh and flavorful."),
        (93,  5.0, "Zach",     "So fresh and milky, perfect for Caprese salad."),
        (93,  4.5, "Amy",      "Great fresh mozzarella, creamy and delicious."),
        (93,  4.5, "Bob",      "Excellent quality, melts beautifully on pizza."),
        (94,  4.5, "Cara",     "Rich and thick, whips up beautifully."),
        (94,  4.0, "Dave",     "Good heavy cream, reliable quality."),
        (94,  4.5, "Eve",      "Perfect for pasta sauces and desserts."),
        # ── Condiments ────────────────────────────────────────────────────────
        (95,  4.5, "Frank",    "Love that there's no corn syrup, great organic."),
        (95,  4.0, "Grace",    "Tastes just like real ketchup should."),
        (95,  4.5, "Henry",    "Best ketchup for my kids, no nasty ingredients."),
        (96,  4.5, "Iris",     "Perfectly sharp and tangy Dijon."),
        (96,  4.0, "Jake",     "Good mustard, great on sandwiches and hot dogs."),
        (96,  5.0, "Kim",      "Authentic Dijon flavor, love this."),
        (97,  4.0, "Leo",      "Classic mayo flavor, smooth and creamy."),
        (97,  4.5, "Mia",      "Made with real eggs, love the quality."),
        (97,  4.0, "Ned",      "Good mayo, great for making sandwiches."),
        (98,  4.5, "Olivia",   "Perfect heat level, love the vinegary kick."),
        (98,  5.0, "Pete",     "A household staple, goes on everything."),
        (98,  4.5, "Quinn",    "Classic hot sauce, love the cayenne flavor."),
        (99,  4.5, "Rose",     "Great low-sodium soy sauce, still very flavorful."),
        (99,  4.0, "Sam",      "Good soy sauce, love the umami depth."),
        (99,  4.5, "Tina",     "Much better than regular soy sauce, lower salt."),
        (100, 5.0, "Uma",      "Best BBQ sauce, organic and so flavorful."),
        (100, 4.5, "Victor",   "Great smoky flavor, love the organic ingredients."),
        (100, 5.0, "Will",     "Makes ribs incredible, highly recommend."),
        (101, 4.5, "Xena",     "Smooth and rich tahini, perfect for hummus."),
        (101, 5.0, "Yael",     "Best tahini I've used, very fresh and nutty."),
        (101, 4.5, "Zach",     "Love the pure sesame flavor, no additives."),
        (102, 5.0, "Amy",      "Perfect heat and garlic balance."),
        (102, 4.5, "Bob",      "Goes on everything! A kitchen essential."),
        (102, 5.0, "Cara",     "The best sriracha, perfect consistency."),
        # ── Canned Goods ──────────────────────────────────────────────────────
        (103, 4.5, "Dave",     "Great organic black beans, firm texture."),
        (103, 4.0, "Eve",      "Good value, perfectly cooked beans."),
        (103, 4.5, "Frank",    "Love the no-salt version, control your seasoning."),
        (104, 4.5, "Grace",    "Great for pasta sauces, perfect tomato flavor."),
        (104, 4.0, "Henry",    "Good quality canned tomatoes, very versatile."),
        (104, 4.0, "Iris",     "Reliable and fresh-tasting, great pantry staple."),
        (105, 4.5, "Jake",     "Perfect chickpeas, creamy and firm."),
        (105, 4.0, "Kim",      "Good quality garbanzo beans, great in salads."),
        (105, 4.5, "Leo",      "Love these for homemade hummus."),
        (106, 4.5, "Mia",      "Pure pumpkin, great for holiday baking."),
        (106, 5.0, "Ned",      "Best pumpkin puree, so smooth and organic."),
        (106, 4.5, "Olivia",   "Perfect for pumpkin pie and soups."),
        (107, 4.5, "Pete",     "Rich and thick, great for coconut curry."),
        (107, 4.0, "Quinn",    "Good coconut cream, love the fat content."),
        (107, 4.5, "Rose",     "Perfect for tropical desserts and curries."),
        (108, 5.0, "Sam",      "Best tomato sauce, organic basil flavor is perfect."),
        (108, 4.5, "Tina",     "Great quality pasta sauce, very flavorful."),
        (108, 5.0, "Uma",      "Love this organic sauce, use it every week."),
        (109, 4.0, "Victor",   "Sweet and crisp, great in salads and soups."),
        (109, 3.5, "Will",     "Decent canned corn, nothing exceptional."),
        (109, 4.0, "Xena",     "Good everyday corn, kids love it."),
        (110, 4.5, "Yael",     "Creamy beans, perfect for Italian dishes."),
        (110, 4.0, "Zach",     "Great white beans, ideal for soups."),
        (110, 4.5, "Amy",      "Love cannellini beans, these are great quality."),
        # ── Breakfast Foods ───────────────────────────────────────────────────
        (111, 5.0, "Bob",      "Rich dark maple syrup, incredible on pancakes."),
        (111, 5.0, "Cara",     "Organic and so flavorful, totally worth it."),
        (111, 4.5, "Dave",     "Best maple syrup, great robust Grade A flavor."),
        (112, 4.5, "Eve",      "Makes perfect fluffy pancakes every time."),
        (112, 4.0, "Frank",    "Easy to use mix, good whole grain flavor."),
        (112, 4.5, "Grace",    "Great for weekend pancakes, hearty and delicious."),
        (113, 4.0, "Henry",    "Classic crispy corn flakes, great with milk."),
        (113, 3.5, "Iris",     "A bit sweet but good everyday cereal."),
        (113, 4.0, "Jake",     "Good classic cereal, stays crispy."),
        (114, 4.5, "Kim",      "Chewy and satisfying, great for snacking."),
        (114, 4.0, "Leo",      "Kids love these, good on-the-go option."),
        (114, 4.5, "Mia",      "Great granola bars, not too sweet."),
        (115, 5.0, "Ned",      "Best muesli I've had, love the fruit and nut mix."),
        (115, 4.5, "Olivia",   "Authentic European muesli, organic and delicious."),
        (115, 4.5, "Pete",     "Love having this with yogurt for breakfast."),
        (116, 4.0, "Quinn",    "Convenient and tasty frozen waffles."),
        (116, 3.5, "Rose",     "Decent waffles for a quick breakfast."),
        (116, 4.0, "Sam",      "Kids love these, great on busy mornings."),
        # ── Baking ────────────────────────────────────────────────────────────
        (117, 4.5, "Tina",     "Perfect all-purpose flour, great for all baking."),
        (117, 4.5, "Uma",      "Reliable quality, use it for everything."),
        (117, 4.0, "Victor",   "Good flour, consistent results every time."),
        (118, 5.0, "Will",     "Love the unbleached organic cane sugar."),
        (118, 4.5, "Xena",     "Great organic sugar, slightly molasses flavor."),
        (118, 4.5, "Yael",     "Much better than conventional white sugar."),
        (119, 4.5, "Zach",     "Great aluminum-free baking powder, works perfectly."),
        (119, 4.0, "Amy",      "Good baking powder, reliable results."),
        (119, 4.5, "Bob",      "Love the aluminum-free formula for clean baking."),
        (120, 5.0, "Cara",     "Best vanilla extract, incredible Madagascar flavor."),
        (120, 5.0, "Dave",     "Pure and intense vanilla, worth every penny."),
        (120, 4.5, "Eve",      "Great vanilla extract, elevates every dessert."),
        (121, 5.0, "Frank",    "Perfect chocolate chips, melt beautifully in cookies."),
        (121, 4.5, "Grace",    "Rich dark chocolate flavor, great for baking."),
        (121, 5.0, "Henry",    "Best chocolate chips, consistently great results."),
        (122, 4.5, "Iris",     "Great coconut flour, love the high fiber content."),
        (122, 4.0, "Jake",     "Good GF flour alternative, absorbs lots of liquid."),
        (122, 4.5, "Kim",      "Love this for paleo baking, works really well."),
        # ── Legumes ───────────────────────────────────────────────────────────
        (123, 5.0, "Leo",      "Cooks so quickly, perfect for weeknight dal."),
        (123, 4.5, "Mia",      "Great organic lentils, very fresh."),
        (123, 4.5, "Ned",      "Love red lentils, these are excellent quality."),
        (124, 4.0, "Olivia",   "Great for thick pea soup, good quality."),
        (124, 4.0, "Pete",     "Classic split peas, hearty and satisfying."),
        (124, 3.5, "Quinn",    "Decent split peas, takes a while to cook."),
        (125, 4.5, "Rose",     "Great sprouted mung beans, very nutritious."),
        (125, 4.5, "Sam",      "Love mung beans, these are excellent organic quality."),
        (125, 4.0, "Tina",     "Good mung beans, great for Indian cooking."),
        (126, 4.0, "Uma",      "Good pinto beans, essential for Mexican cooking."),
        (126, 4.0, "Victor",   "Classic pinto beans, reliable quality."),
        (126, 3.5, "Will",     "Decent beans, took longer to cook than expected."),
        (127, 4.5, "Xena",     "Great black-eyed peas, creamy when cooked."),
        (127, 4.5, "Yael",     "Love these for Southern-style dishes."),
        (127, 4.0, "Zach",     "Good organic black-eyed peas, great value."),
        # ── Chocolate ─────────────────────────────────────────────────────────
        (128, 5.0, "Amy",      "Complex bittersweet flavor, excellent quality."),
        (128, 4.5, "Bob",      "Love 70% cacao, perfect dark chocolate."),
        (128, 5.0, "Cara",     "Best dark chocolate bar I've ever tasted."),
        (129, 5.0, "Dave",     "Creamy and rich, ethically sourced cocoa."),
        (129, 4.5, "Eve",      "Love the organic milk chocolate, smooth texture."),
        (129, 4.5, "Frank",    "Great milk chocolate, not too sweet."),
        (130, 4.0, "Grace",    "Good white chocolate chips for baking."),
        (130, 4.0, "Henry",    "Decent quality, melts well in recipes."),
        (130, 3.5, "Iris",     "A bit too sweet but works well for cookies."),
        (131, 5.0, "Jake",     "Incredible raw cacao, so rich and healthy."),
        (131, 4.5, "Kim",      "Love adding to smoothies, great organic quality."),
        (131, 5.0, "Leo",      "Best cacao powder, intense and antioxidant-rich."),
        (132, 5.0, "Mia",      "Perfect combination of chocolate and almonds."),
        (132, 4.5, "Ned",      "Great snack, love the dark chocolate coating."),
        (132, 4.5, "Olivia",   "Addictive in the best way possible!"),
        (133, 4.5, "Pete",     "Classic gummy bears, fruity and chewy."),
        (133, 4.0, "Quinn",    "Fun snack, kids and adults both love these."),
        (133, 4.5, "Rose",     "Great gummy bears, lots of variety in flavors."),
        # ── Spreads ───────────────────────────────────────────────────────────
        (134, 5.0, "Sam",      "Just peanuts and salt, exactly how it should be."),
        (134, 4.5, "Tina",     "Love natural PB, no oil separation issues."),
        (134, 5.0, "Uma",      "Best natural peanut butter I've tried."),
        (135, 5.0, "Victor",   "Smooth and pure, just almonds, no additives."),
        (135, 4.5, "Will",     "Worth the price, incredible organic almond butter."),
        (135, 5.0, "Xena",     "Best nut butter, love the organic quality."),
        (136, 4.5, "Yael",     "Classic strawberry jam, great fruity flavor."),
        (136, 4.0, "Zach",     "Good jam, love on toast with butter."),
        (136, 4.5, "Amy",      "Great everyday strawberry jam."),
        (137, 5.0, "Bob",      "Intense raspberry flavor, love the organic quality."),
        (137, 4.5, "Cara",     "Great preserves, real chunks of fruit."),
        (137, 5.0, "Dave",     "Best raspberry preserves I've ever had."),
        (138, 5.0, "Eve",      "Everyone's favorite, rich hazelnut chocolate spread."),
        (138, 4.5, "Frank",    "Amazing on crepes and toast."),
        (138, 4.5, "Grace",    "Classic taste, love it with bananas."),
        (139, 4.5, "Henry",    "Great nut-free option, love sunflower seed butter."),
        (139, 4.5, "Iris",     "Perfect for allergy-friendly households."),
        (139, 4.0, "Jake",     "Good alternative to peanut butter, mild and creamy."),
        # ── Soups ─────────────────────────────────────────────────────────────
        (140, 5.0, "Kim",      "Rich and flavorful organic chicken broth."),
        (140, 4.5, "Leo",      "Love the slow-simmered depth of flavor."),
        (140, 5.0, "Mia",      "Best organic broth, great for soups and risottos."),
        (141, 4.5, "Ned",      "Great vegetable broth, rich in vegetable flavor."),
        (141, 4.0, "Olivia",   "Good quality broth, great for vegetarian cooking."),
        (141, 4.5, "Pete",     "Love this for making vegetable risotto."),
        (142, 5.0, "Quinn",    "Best tomato soup, creamy and organic."),
        (142, 4.5, "Rose",     "Restaurant-quality tomato soup at home!"),
        (142, 5.0, "Sam",      "Love the basil flavor, perfect organic soup."),
        (143, 4.5, "Tina",     "Hearty and filling, great lentil soup."),
        (143, 4.0, "Uma",      "Good ready-to-eat soup, convenient and healthy."),
        (143, 4.0, "Victor",   "Decent lentil soup, satisfying and warm."),
        (144, 5.0, "Will",     "Best bone broth, incredibly rich and collagen-packed."),
        (144, 4.5, "Xena",     "Great for gut health, sip it like tea."),
        (144, 5.0, "Yael",     "Love making soups with this, incredible depth."),
        # ── Chips & Crackers ──────────────────────────────────────────────────
        (145, 4.5, "Zach",     "Crunchy organic tortilla chips, great with guac."),
        (145, 4.5, "Amy",      "Love the organic quality, not too salty."),
        (145, 5.0, "Bob",      "Best tortilla chips for guacamole and salsa."),
        (146, 5.0, "Cara",     "Incredibly crunchy kettle chips, love sea salt."),
        (146, 4.5, "Dave",     "Best kettle chips, perfectly seasoned."),
        (146, 5.0, "Eve",      "Addictively crunchy, love the kettle cooked style."),
        (147, 4.0, "Frank",    "Light and crispy, great gluten-free cracker."),
        (147, 4.0, "Grace",    "Good rice crackers, great with dips and cheese."),
        (147, 3.5, "Henry",    "A bit bland alone but good with toppings."),
        (148, 4.5, "Iris",     "Great whole grain pretzels, satisfying crunch."),
        (148, 4.0, "Jake",     "Good pretzels, love the whole grain twist."),
        (148, 4.5, "Kim",      "Perfect salty snack, love these pretzels."),
        (149, 4.5, "Leo",      "Perfect with hummus, love the baked pita chips."),
        (149, 4.0, "Mia",      "Good pita chips, great for parties and dips."),
        (149, 4.5, "Ned",      "Excellent crunch, love the original flavor."),
        (150, 4.5, "Olivia",   "Great grain-free chips, love the cassava flour."),
        (150, 5.0, "Pete",     "Best paleo chips I've found, incredible crunch."),
        (150, 4.5, "Quinn",    "Perfect for grain-free snacking, love these."),
        # ── Supplements ───────────────────────────────────────────────────────
        (151, 5.0, "Rose",     "Best organic whey, clean ingredients and great taste."),
        (151, 4.5, "Sam",      "Love grass-fed whey, mixes well and tastes great."),
        (151, 4.5, "Tina",     "Great organic protein powder, no bloating issues."),
        (152, 4.5, "Uma",      "Love liquid D3, absorbs better than pills."),
        (152, 4.0, "Victor",   "Good Vitamin D supplement, easy to take."),
        (152, 4.5, "Will",     "Great product, noticed improvement in mood."),
        (153, 5.0, "Xena",     "Incredible stress relief, noticeable difference."),
        (153, 4.5, "Yael",     "Love organic ashwagandha, helps with anxiety."),
        (153, 4.5, "Zach",     "Great adaptogen supplement, very calming."),
        (154, 4.5, "Amy",      "High quality fish oil, no fishy aftertaste."),
        (154, 4.0, "Bob",      "Good EPA+DHA content, easy to swallow softgels."),
        (154, 4.5, "Cara",     "Love this fish oil, joints feel much better."),
        (155, 5.0, "Dave",     "Best spirulina, incredible nutrient density."),
        (155, 4.5, "Eve",      "Great organic spirulina, love in smoothies."),
        (155, 4.5, "Frank",    "Superfood powder, mix into anything easily."),
        # ── Frozen Foods ──────────────────────────────────────────────────────
        (156, 5.0, "Grace",    "Sweet and tender, taste just like fresh peas."),
        (156, 4.5, "Henry",    "Great organic frozen peas, very convenient."),
        (156, 4.5, "Iris",     "Love these for quick weeknight sides."),
        (157, 4.5, "Jake",     "Great mixed berries for smoothies and desserts."),
        (157, 4.0, "Kim",      "Good quality frozen berries, lots of variety."),
        (157, 4.5, "Leo",      "Love the large bag, great value and quality."),
        (158, 5.0, "Mia",      "Ready-to-eat edamame is so convenient!"),
        (158, 4.5, "Ned",      "Great organic edamame, perfect protein snack."),
        (158, 4.5, "Olivia",   "Love these for a healthy quick snack."),
        (159, 4.5, "Pete",     "Great frozen broccoli, great for stir-fries."),
        (159, 4.0, "Quinn",    "Convenient and nutritious frozen broccoli."),
        (159, 4.0, "Rose",     "Good broccoli florets, holds texture when cooked."),
        (160, 4.5, "Sam",      "Great low-carb rice alternative, love cauliflower rice."),
        (160, 4.0, "Tina",     "Good texture, great for keto cooking."),
        (160, 4.5, "Uma",      "Love the convenience of ready-to-cook cauli rice."),
        (161, 4.5, "Victor",   "Sweet organic corn, tastes almost fresh."),
        (161, 4.5, "Will",     "Great frozen corn, love the organic quality."),
        (161, 4.0, "Xena",     "Good corn kernels, versatile for many dishes."),
        (162, 4.5, "Yael",     "Great plant-based burgers, holds together well."),
        (162, 4.0, "Zach",     "Good veggie burgers, tasty and high in protein."),
        (162, 4.5, "Amy",      "Love veggie patties, great for Meatless Monday."),
        (163, 4.5, "Bob",      "Organic waffles that actually taste great!"),
        (163, 5.0, "Cara",     "Best frozen waffles, love the whole grain organic."),
        (163, 4.5, "Dave",     "Great breakfast option, organic and delicious."),
        # ── Baby Food ─────────────────────────────────────────────────────────
        (164, 5.0, "Eve",      "My baby loves this! Pure organic and healthy."),
        (164, 4.5, "Frank",    "Great organic baby food, clean ingredients."),
        (164, 4.5, "Grace",    "Love the pea and spinach combo, very nutritious."),
        (165, 5.0, "Henry",    "Best baby oatmeal, smooth and easy to digest."),
        (165, 4.5, "Iris",     "Great iron-fortified oatmeal for our baby."),
        (165, 4.5, "Jake",     "Organic baby cereal that baby actually enjoys."),
        (166, 4.5, "Kim",      "Perfect first food for our baby, sweet and smooth."),
        (166, 4.0, "Leo",      "Good sweet potato puree, baby enjoys it."),
        (166, 4.5, "Mia",      "Great stage 1 baby food, all natural."),
        (167, 5.0, "Ned",      "These teething crackers are a lifesaver!"),
        (167, 4.5, "Olivia",   "Baby loves these, dissolves safely and quickly."),
        (167, 4.5, "Pete",     "Great organic teething crackers, no worries."),
        # ── Deli ──────────────────────────────────────────────────────────────
        (168, 5.0, "Quinn",    "Best hummus, creamy and perfectly flavored."),
        (168, 4.5, "Rose",     "Love the olive oil drizzle, authentic taste."),
        (168, 5.0, "Sam",      "Best store-bought hummus I've tried."),
        (169, 5.0, "Tina",     "Fresh and authentic, love the lime and cilantro."),
        (169, 4.5, "Uma",      "Great organic guac, love the chunky texture."),
        (169, 5.0, "Victor",   "Best guacamole, tastes freshly made."),
        (170, 4.5, "Will",     "Creamy and tangy, perfect Greek tzatziki."),
        (170, 4.0, "Xena",     "Good tzatziki, great with pita bread."),
        (170, 4.5, "Yael",     "Love the dill flavor, very authentic."),
        (171, 4.5, "Zach",     "Easy weeknight dinner, great Mediterranean flavor."),
        (171, 4.0, "Amy",      "Good pre-marinated chicken, very convenient."),
        (171, 4.5, "Bob",      "Love the Mediterranean spices, delicious grilled."),
        (172, 5.0, "Cara",     "Best organic salsa, love the chunky texture."),
        (172, 4.5, "Dave",     "Great medium heat, perfect with tortilla chips."),
        (172, 5.0, "Eve",      "Love the fresh jalapeño flavor, top quality."),
        (173, 4.5, "Frank",    "Incredible smoked salmon spread, restaurant quality."),
        (173, 4.0, "Grace",    "Great on bagels, love the smoked salmon flavor."),
        (173, 4.5, "Henry",    "Delicious spread, love the combination."),
        # ── Protein Bars ──────────────────────────────────────────────────────
        (174, 4.5, "Iris",     "Classic energy bar, great before workouts."),
        (174, 4.0, "Jake",     "Good sustained energy, love chocolate chip."),
        (174, 4.5, "Kim",      "My go-to hiking bar, great organic oats."),
        (175, 5.0, "Leo",      "Incredible whole food bar, love almond coconut."),
        (175, 4.5, "Mia",      "Great clean ingredients, very satisfying snack."),
        (175, 4.5, "Ned",      "Love Kind bars, great for on-the-go snacking."),
        (176, 5.0, "Olivia",   "Best minimal ingredient bars, love organic Larabar."),
        (176, 4.5, "Pete",     "Clean and delicious, love the organic quality."),
        (176, 4.5, "Quinn",    "Great natural bars, kids and adults love them."),
        (177, 4.5, "Rose",     "High protein and delicious, love cookies & cream."),
        (177, 4.0, "Sam",      "Good macros, great for hitting protein goals."),
        (177, 4.5, "Tina",     "Best high-protein bar taste-wise."),
        (178, 5.0, "Uma",      "Love the clean ingredient list, incredible bars."),
        (178, 4.5, "Victor",   "Best protein bars, whole food ingredients only."),
        (178, 4.5, "Will",     "Love the chocolate sea salt combo, very satisfying."),
        # ── Herbs ─────────────────────────────────────────────────────────────
        (179, 5.0, "Xena",     "So fragrant and fresh, makes incredible pesto."),
        (179, 4.5, "Yael",     "Beautiful fresh basil, lasts well in the fridge."),
        (179, 4.5, "Zach",     "Great quality basil, love for Italian cooking."),
        (180, 4.5, "Amy",      "Super fresh organic mint, great for teas."),
        (180, 5.0, "Bob",      "Love fresh mint in mojitos and desserts!"),
        (180, 4.5, "Cara",     "Great organic mint, very aromatic and fresh."),
        (181, 5.0, "Dave",     "Essential for Mexican cooking, very fresh."),
        (181, 4.5, "Eve",      "Love fresh cilantro, great quality."),
        (181, 4.0, "Frank",    "Good fresh cilantro, love in salsas and tacos."),
        (182, 5.0, "Grace",    "Incredible fragrant rosemary, great for roasting."),
        (182, 4.5, "Henry",    "Love fresh organic rosemary with roast chicken."),
        (182, 4.5, "Iris",     "Great quality, very fragrant and fresh."),
        # ── Jams & Preserves ──────────────────────────────────────────────────
        (183, 4.5, "Jake",     "Delicious blueberry jam, real fruit flavor."),
        (183, 4.0, "Kim",      "Good jam, love blueberry flavor on toast."),
        (183, 4.5, "Leo",      "Great fruity blueberry jam, not too sweet."),
        (184, 5.0, "Mia",      "Best apricot preserves, real chunky fruit!"),
        (184, 4.5, "Ned",      "Organic and so flavorful, love apricot jam."),
        (184, 4.5, "Olivia",   "Perfect with cheese and crackers."),
        (185, 4.5, "Pete",     "Classic British marmalade, love the peel."),
        (185, 4.0, "Quinn",    "Good orange marmalade, bittersweet perfection."),
        (185, 4.5, "Rose",     "Love marmalade on sourdough, great flavor."),
        (186, 5.0, "Sam",      "Incredible fig jam, pairs perfectly with brie."),
        (186, 4.5, "Tina",     "Love organic fig jam, thick and delicious."),
        (186, 5.0, "Uma",      "Best fig jam I've ever tasted."),
        # ── More Tea & Coffee ─────────────────────────────────────────────────
        (187, 5.0, "Victor",   "Ceremonial grade quality, incredible umami flavor."),
        (187, 4.5, "Will",     "Best matcha I've tried, very smooth and frothy."),
        (187, 5.0, "Xena",     "Love this organic matcha, makes perfect lattes."),
        (188, 4.5, "Yael",     "Authentic yerba mate, great energy boost."),
        (188, 4.0, "Zach",     "Traditional flavor, great introduction to mate."),
        (188, 4.5, "Amy",      "Love yerba mate, great caffeine alternative."),
        (189, 4.5, "Bob",      "Beautiful deep red color, tart and refreshing."),
        (189, 4.0, "Cara",     "Good hibiscus tea, naturally caffeine-free."),
        (189, 4.5, "Dave",     "Love iced hibiscus tea in the summer."),
        (190, 5.0, "Eve",      "Golden milk is my new bedtime ritual!"),
        (190, 4.5, "Frank",    "Love the turmeric ginger blend, very warming."),
        (190, 4.5, "Grace",    "Great anti-inflammatory drink, delicious with oat milk."),
        (191, 4.0, "Henry",    "Great decaf option, no compromise on flavor."),
        (191, 4.0, "Iris",     "Good decaf Colombian, smooth and satisfying."),
        (191, 3.5, "Jake",     "Decent decaf, slightly weaker than regular."),
        (192, 4.5, "Kim",      "Love the natural hazelnut flavor, not artificial."),
        (192, 4.0, "Leo",      "Great hazelnut coffee, smooth and aromatic."),
        (192, 4.5, "Mia",      "Perfect morning coffee with dessert vibes."),
        (193, 5.0, "Ned",      "Game-changing coffee, love the mushroom benefits."),
        (193, 4.5, "Olivia",   "Great focus and energy without the jitters."),
        (193, 5.0, "Pete",     "Best mushroom coffee, love lion's mane effect."),
        # ── More Pasta & Grains ───────────────────────────────────────────────
        (194, 4.5, "Quinn",    "Great orzo for soup, cooks quickly and evenly."),
        (194, 4.0, "Rose",     "Good pasta shape, versatile for many dishes."),
        (194, 4.5, "Sam",      "Love orzo in Greek salads, great texture."),
        (195, 4.5, "Tina",     "Incredible protein content, holds texture well."),
        (195, 4.5, "Uma",      "Best gluten-free pasta alternative I've tried."),
        (195, 4.0, "Victor",   "Love the red lentil pasta, great protein boost."),
        (196, 5.0, "Will",     "Ancient grain with incredible nutty flavor."),
        (196, 4.5, "Xena",     "Love farro in salads, great chewy texture."),
        (196, 4.5, "Yael",     "Best farro I've cooked, very fresh."),
        (197, 4.5, "Zach",     "Great tiny grain, love popped amaranth on salads."),
        (197, 4.0, "Amy",      "Good gluten-free grain, mild flavor."),
        (197, 4.0, "Bob",      "Nutritious ancient grain, takes time to discover."),
        (198, 4.5, "Cara",     "Versatile grain, great as rice substitute."),
        (198, 4.5, "Dave",     "Love organic millet, light and fluffy when cooked."),
        (198, 4.0, "Eve",      "Good grain, great for gluten-free cooking."),
        (199, 4.5, "Frank",    "Love pearl couscous in salads, great texture."),
        (199, 4.0, "Grace",    "Good quality, cooks in about 10 minutes."),
        (199, 4.5, "Henry",    "Great for Mediterranean dishes and grain bowls."),
        (200, 5.0, "Iris",     "Nutty roasted flavor, great kasha porridge."),
        (200, 4.5, "Jake",     "Love organic buckwheat, earthy and satisfying."),
        (200, 4.5, "Kim",      "Best buckwheat groats, great for breakfast bowls."),
        (201, 4.5, "Leo",      "Perfect everyday white rice, fluffy and light."),
        (201, 4.0, "Mia",      "Good quality long grain rice, reliable."),
        (201, 4.5, "Ned",      "Great rice, cooks perfectly every time."),
        (202, 5.0, "Olivia",   "Most fragrant jasmine rice I've cooked at home."),
        (202, 4.5, "Pete",     "Love the floral aroma, authentic Thai rice."),
        (202, 5.0, "Quinn",    "Best jasmine rice, pairs with everything."),
        (203, 5.0, "Rose",     "Incredibly aromatic aged basmati, restaurant-quality."),
        (203, 4.5, "Sam",      "Perfect Indian basmati, long and fluffy grains."),
        (203, 5.0, "Tina",     "Best basmati rice for biryani and pilaf."),
        (204, 4.5, "Uma",      "Makes perfect creamy polenta, great stone-ground."),
        (204, 4.0, "Victor",   "Good cornmeal, great for cornbread and polenta."),
        (204, 4.5, "Will",     "Love this for Southern-style cornbread."),
        (205, 5.0, "Xena",     "Incredible iron content, love baking with teff."),
        (205, 4.5, "Yael",     "Great ancient grain flour, slightly nutty flavor."),
        (205, 4.5, "Zach",     "Love organic teff, great for gluten-free baking."),
        # ── More Nuts & Seeds ─────────────────────────────────────────────────
        (206, 5.0, "Amy",      "Incredibly fresh walnuts, great omega-3 boost."),
        (206, 4.5, "Bob",      "Love organic walnuts, great in salads and baking."),
        (206, 4.5, "Cara",     "Best walnuts I've bought, very fresh and crisp."),
        (207, 4.5, "Dave",     "Perfectly roasted pepitas, great snack."),
        (207, 4.0, "Eve",      "Good pumpkin seeds, love on salads."),
        (207, 4.5, "Frank",    "Great lightly salted pepitas, very addictive."),
        (208, 5.0, "Grace",    "Fresh organic sunflower seeds, love them."),
        (208, 4.5, "Henry",    "Great for salads and snacking, organic quality."),
        (208, 4.5, "Iris",     "Love organic sunflower seeds, great value."),
        (209, 4.5, "Jake",     "Ground flaxseeds into smoothies, very nutritious."),
        (209, 4.5, "Kim",      "Great organic flaxseeds, love the omega-3 boost."),
        (209, 4.0, "Leo",      "Good flaxseeds, excellent fiber source."),
        (210, 5.0, "Mia",      "Buttery and rich, best macadamia nuts ever!"),
        (210, 5.0, "Ned",      "Hawaiian macadamia nuts are incredible, so fresh."),
        (210, 4.5, "Olivia",   "Worth every penny, premium macadamia quality."),
        (211, 5.0, "Pete",     "Best organic pecans, incredibly sweet and buttery."),
        (211, 4.5, "Quinn",    "Love organic pecans, great for baking and snacking."),
        (211, 5.0, "Rose",     "Freshest pecans I've ever bought, wonderful quality."),
    ]

    cursor.execute("DELETE FROM reviews")
    cursor.executemany(
        "INSERT INTO reviews (product_id, rating, reviewer_name, review_text) VALUES (?, ?, ?, ?)",
        reviews,
    )

    conn.commit()
    conn.close()
    print(f"Database created at: {DB_PATH}")
    print(f"Total products: {len(products)}")
    print(f"Total reviews: {len(reviews)}")


if __name__ == "__main__":
    create_database()
